### PR TITLE
Lightning Dragons

### PR DESCRIPTION
**Pull request by Mellohi138**
Seeing as RLCraft also added lightning dragons, I think we no longer need any reason to hold this back.

### CODE REVIEW

**Comment by MagmaSlime123** [comment]
Does this include all items for them?

**Comment by democat3457** [comment]
You can check the new version yourself, we might've missed some

**Comment by MagmaSlime123** [comment]
> You can check the new version yourself, we might've missed some

A Spartan Weaponry I&F fork that adds lightning dragonsteel weapons would be neat. That seems to be the only missing thing. Also, no Ghost stuff.

**Comment by MagmaSlime123** [comment]
Umm... Heads up, it seems dragon AI is acting very weird. They fly in a straight line into the distance then de-spawn. Happens every time a nest with a dragon generates. Happens ever since this version came out.

**Pull request merged**
